language: php
sudo: false
php:
  - 7.2
  - 7.3
install:
  - composer install
script:
  - php vendor/bin/phpunit --coverage-clover build/coverage/xml
after_script:
  - php vendor/bin/codacycoverage clover build/coverage/xml